name = "SurvivalModels"
uuid = "230d35e3-bb2c-48f4-adfc-0b42c4b39395"
authors = ["Oskar Laverny <oskar.laverny@univ-amu.fr> and contributors"]
version = "0.1.0"

[compat]
Aqua = "0.8"
julia = "1.6.7"
Test = "1.6"
TestItemRunner = "0.2"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Test", "TestItemRunner"]
